baseURL = "https://shotanue.github.io/"
languageCode = "ja-JP"
defaultContentLanguage = "en"

title = "@shotanue"
theme = "hermit"

publishDir = "../"


#@ref https://github.com/Track3/hermit/blob/master/exampleSite/config.toml
[author]
  #footerに名前が入る
  name = ""

[params]
  #日付の形式を指定する
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
 
  homeSubtitle = ""

  code_copy_button = true # Turn on/off the code-copy-button for code-fields
  

  # Social Icons
  # Check https://github.com/Track3/hermit#social-icons for more info.
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/shotanue"

  [[params.social]]
    name = "github"
    url = "https://github.com/shotanue"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "posts/"
    weight = 10

#  [[menu.main]]
#    name = "About"
#    url = "about-hugo/"
#    weight = 20

